- type: job
  id: Passenger
  name: job-name-passenger
  description: job-description-passenger
  playTimeTracker: JobPassenger
  startingGear: PassengerGear
  icon: "JobIconPassenger"
  supervisors: job-supervisors-everyone
  access:
  - Maintenance
  special:
  - !type:AddComponentSpecial
    components:
      - type: Statistics
        attributes:
          Strength: 9
          Dexterity: 9
          Intelligence: 9
          Will: 9

- type: startingGear
  id: PassengerGear
  subGear:
  - PassengerPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorGrey
    back: ClothingBackpackFilled
    shoes: ClothingShoesColorBlack
    id: PassengerPDA
    ears: ClothingHeadsetGrey
  innerClothingSkirt: ClothingUniformJumpskirtColorGrey
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled

- type: startingGear
  id: PassengerPlasmamanGear
  parent: BasePlasmamanGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitColorGrey
    head: ClothingHeadEnvirohelmColorGrey
    gloves: ClothingHandsGlovesEnviroglovesColorDarkGrey
