- type: job
  id: Janitor
  name: job-name-janitor
  description: job-description-janitor
  playTimeTracker: JobJanitor
  startingGear: JanitorGear
  icon: "JobIconJanitor"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Janitor
  - Maintenance
  special:
  - !type:AddComponentSpecial
    components:
      - type: Statistics
        attributes:
          Strength: 10
          Dexterity: 10
          Intelligence: 11
          Will: 10
        skills:
          Housekeeping: 6
  - !type:GiveItemOnHolidaySpecial
    holiday: GarbageDay
    prototype: WeaponRevolverInspector
  requirements:
    - !type:CharacterEmployerRequirement
      inverted: true
      employers:
      - Unemployed

- type: startingGear
  id: JanitorGear
  subGear:
  - JanitorPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitJanitor
    back: ClothingBackpackFilled
    shoes: ClothingShoesGaloshes
    head: ClothingHeadHatPurplesoft
    id: JanitorPDA
    gloves: ClothingHandsGlovesJanitor
    ears: ClothingHeadsetService
    belt: ClothingBeltJanitorFilled
  innerClothingSkirt: ClothingUniformJumpskirtJanitor
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled

- type: startingGear
  id: JanitorPlasmamanGear
  parent: BasePlasmamanGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitJanitor
    head: ClothingHeadEnvirohelmJanitor
    gloves: ClothingHandsGlovesEnviroglovesJanitor

- type: startingGear
  id: JanitorMaidGear
  equipment:
    jumpsuit: ClothingUniformJumpskirtJanimaid
    back: ClothingBackpackFilled
    id: JanitorPDA
    gloves: ClothingHandsGlovesJanitor
    head: ClothingHeadHatCatEars
    ears: ClothingHeadsetService
    belt: ClothingBeltJanitorFilled
  innerClothingSkirt: ClothingUniformJumpskirtJanimaid
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
