- type: job
  id: ResearchAssistant
  name: job-name-research-assistant
  description: job-description-research-assistant
  playTimeTracker: JobResearchAssistant
  requirements:
    # - !type:DepartmentTimeRequirement # DeltaV - Removes time limit
    #   department: Science
    #   time: 54000 #15 hrs
    #   inverted: true # stop playing intern if you're good at science!
    - !type:CharacterEmployerRequirement
      inverted: true
      employers:
      - Unemployed
  startingGear: ResearchAssistantGear
  icon: "JobIconResearchAssistant"
  supervisors: job-supervisors-science
  canBeAntag: true # DeltaV - Can be antagonist
  access:
  - Research
  - Maintenance
  special:
  - !type:AddComponentSpecial
  components:
    - type: Statistics
      attributes:
        Strength: 7
        Dexterity: 8
        Intelligence: 11
        Will: 10
      skills:
        Electrician: 1
        Mechanic: 1
        Housekeeping: 2

- type: startingGear
  id: ResearchAssistantGear
  subGear:
  - ScientistPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorWhite
    back: ClothingBackpackScienceFilled
    shoes: ClothingShoesColorWhite
    id: ResearchAssistantPDA
    ears: ClothingHeadsetScience
    pocket1: BookPsionicsGuidebook
    pocket2: BookScientistsGuidebook
  innerClothingSkirt: ClothingUniformJumpskirtColorWhite
  satchel: ClothingBackpackSatchelScienceFilled
  duffelbag: ClothingBackpackDuffelScienceFilled
