- type: job
  id: Roboticist
  name: job-name-roboticist
  description: job-description-roboticist
  playTimeTracker: JobRoboticist
  requirements:
  - !type:CharacterDepartmentTimeRequirement
    department: Epistemics
    min: 14400 # 4 hours - same as scientist
  - !type:CharacterEmployerRequirement
    inverted: true
    employers:
    - Unemployed
  startingGear: RoboticistGear
  icon: "JobIconRoboticist"
  supervisors: job-supervisors-rd
  access:
  - Research
  - Maintenance
  special:
  - !type:AddComponentSpecial
  components:
    - type: Statistics
      attributes:
        Strength: 8
        Dexterity: 9
        Intelligence: 12
        Will: 8
      skills:
        Electrician: 2
        Mechanic: 2

- type: startingGear
  id: RoboticistGear
  subGear:
  - RoboticistPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitRoboticist
    back: ClothingBackpackRoboticsFilled
    shoes: ClothingShoesColorBlack
    outerClothing: ClothingOuterCoatRobo
    id: RoboticsPDA
    ears: ClothingHeadsetRobotics
    pocket1: BookPsionicsGuidebook
  innerClothingSkirt: ClothingUniformJumpskirtRoboticist
  satchel: ClothingBackpackSatchelRoboticsFilled
  duffelbag: ClothingBackpackDuffelRoboticsFilled

- type: startingGear
  id: RoboticistPlasmamanGear
  parent: BasePlasmamanGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitRoboticist
    head: ClothingHeadEnvirohelmRoboticist
    gloves: ClothingHandsGlovesEnviroglovesRoboticist
